// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3P5jLRIJLQtOxiWkALNZoVihdPx-fDlE',
    appId: '1:296108192882:web:610ddad75faf984401feeb',
    messagingSenderId: '296108192882',
    projectId: 'slash-task',
    authDomain: 'slash-task.firebaseapp.com',
    storageBucket: 'slash-task.appspot.com',
    measurementId: 'G-BW7Z00ENWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcAlJDhJwOyOIl9WcQSDy0b6HlDq6Sy4',
    appId: '1:296108192882:android:da16cf88bf70bd0901feeb',
    messagingSenderId: '296108192882',
    projectId: 'slash-task',
    storageBucket: 'slash-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_58vZLX0Q3z9l64-zh2_4D0tamKNCfw',
    appId: '1:296108192882:ios:6d6f22f767eb1dfb01feeb',
    messagingSenderId: '296108192882',
    projectId: 'slash-task',
    storageBucket: 'slash-task.appspot.com',
    iosBundleId: 'com.example.slashTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_58vZLX0Q3z9l64-zh2_4D0tamKNCfw',
    appId: '1:296108192882:ios:c4af03c32ffde02801feeb',
    messagingSenderId: '296108192882',
    projectId: 'slash-task',
    storageBucket: 'slash-task.appspot.com',
    iosBundleId: 'com.example.slashTask.RunnerTests',
  );
}
